sudo: false # route your build to the container-based infrastructure for a faster build

language: ruby

before_install:
  - gem install bundler -v '< 2'

cache:
  # Cache Ruby bundles
  - bundler
  - directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer #https://github.com/gjtorikian/html-proofer/issues/381
  

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: "bash -ex .travis-ci.sh"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

matrix:
  fast_finish: true
  include:
    - rvm: 2.3.0
      env: TASK='htmlproofer'
    - rvm: 2.3.0
      env: TASK='htmlproofer-external'
    - rvm: 2.3.0
      env: TASK='cip-validator'
  allow_failures:
    - rvm: 2.3.0
      env: TASK='htmlproofer-external'

# Notifications
after_success: "bash -ex .travis-ci-notify.sh success $WEBHOOK_URL"

addons:
  apt:
    packages:
      "libcurl4-openssl-dev" # https://github.com/gjtorikian/html-proofer/issues/376#issuecomment-332767999
